version: '3.8'

services:
  api:
    container_name: api
    build:
      context: api/
      dockerfile: api.dockerfile
      target: dev-target
    ports:
      - '5000:5000'
      - '8080:8080'
      - '2345:2345'
    env_file:
      - .env
      - .secrets
    depends_on:
      - mongo
    volumes:
      - ./api:/app:rw,delegated
    networks:
      - backend
  mongo:
    container_name: mongo
    volumes:
      - db-data:/data/db
    networks:
      - backend
    ports:
      - '127.0.0.1:28017:27017'
    restart: always
    build:
      context: db/
      dockerfile: db.dockerfile
    env_file:
      - .env
      - .secrets

  nextjs:
    container_name: nextjs
    build:
      context: nextjs/
      dockerfile: nextjs.dockerfile
      target: test-target
    volumes:
      - type: bind
        source: ./nextjs
        target: /usr/src/app/
    env_file:
      - .env
      - .secrets
    ports:
      - 3000:3000
    command: yarn next dev

volumes:
  db-data: {}

networks:
  backend:
    driver: bridge
