version: '3.8'

services:
  api:
    container_name: api
    build:
      context: api/
      dockerfile: api.dockerfile
      target: dev-target
    command:
      [
        "--listen=:2345",
        "--headless=true",
        "--log=true",
        "--log-output=debugger,debuglineerr",
        "--accept-multiclient",
        "--api-version=2",
        "exec",
        "/app/linkshare_api"
      ]
    ports:
      - '5000:5000'
      - '8080:8080'
      - '2345:2345'
    env_file:
      - .env
      - .secrets
    depends_on:
      - mongo
    volumes:
      - type: bind
        source: api/
        target: /app
    networks:
      - backend
  mongo:
    container_name: mongo
    volumes:
      - db-data:/data/db
    networks:
      - backend
    ports:
      - '127.0.0.1:28017:27017'
    restart: always
    build:
      context: database/
      dockerfile: db.dockerfile
    env_file:
      - .env
      - .secrets

  nextjs:
    container_name: nextjs
    build:
      context: nextjs/
      dockerfile: nextjs.dockerfile
      target: test-target
    volumes:
      - type: bind
        source: ./nextjs
        target: /usr/src/app/
    env_file:
      - .env
      - .secrets
    ports:
      - 3000:3000
    command: yarn next dev

volumes:
  db-data: {}

networks:
  backend:
    driver: bridge
