// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type NewPage struct {
	URL  string `json:"URL"`
	User string `json:"user"`
}

type NewUser struct {
	Username  string  `json:"username"`
	FirstName *string `json:"firstName"`
	Lastname  *string `json:"lastname"`
	Email     *string `json:"email"`
	GoogleID  *string `json:"googleID"`
}

type Page struct {
	URL         string    `json:"URL"`
	Description *string   `json:"description"`
	Title       *string   `json:"title"`
	Links       []*string `json:"links"`
	User        string    `json:"user"`
}

type UpdatePage struct {
	Description *string   `json:"description"`
	Title       *string   `json:"title"`
	Links       []*string `json:"links"`
}

type UpdateUser struct {
	FirstName *string `json:"firstName"`
	Lastname  *string `json:"lastname"`
	Email     *string `json:"email"`
}
