// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type NewPage struct {
	URL  string `json:"URL"`
	User string `json:"user"`
}

type Page struct {
	URL         string    `json:"URL"`
	Description *string   `json:"description"`
	Title       *string   `json:"title"`
	Links       []*string `json:"links"`
	User        string    `json:"user"`
}

type UpdatePage struct {
	Description *string   `json:"description"`
	Title       *string   `json:"title"`
	Links       []*string `json:"links"`
}

type UpdateUser struct {
	Username  *string `json:"username"`
	FirstName *string `json:"firstName"`
	LastName  *string `json:"lastName"`
	Email     *string `json:"email"`
}
