// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type UpdatePage struct {
	Description *string   `json:"description"`
	Title       *string   `json:"title"`
	Links       []*string `json:"links"`
}

type UpdateUser struct {
	Username  *string `json:"username"`
	FirstName *string `json:"firstName"`
	LastName  *string `json:"lastName"`
	Email     *string `json:"email"`
}
